INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Afghanistan', 'Kabul', 34.5553, 69.2075, 'KBL');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Albania', 'Tirana', 41.3275, 19.8189, 'TIA');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Algeria', 'Algiers', 36.7372, 3.0860, 'ALG');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Andorra', 'Andorra la Vella', 42.5078, 1.5211, 'LEU');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Angola', 'Luanda', -8.8390, 13.2894, 'LAD');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Antigua and Barbuda', 'Saint Johns', 17.1175, -61.8456, 'ANU');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Argentina', 'Buenos Aires', -34.6118, -58.4173, 'EZE');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Armenia', 'Yerevan', 40.1792, 44.4991, 'EVN');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Australia', 'Canberra', -35.2820, 149.1287, 'CBR');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Austria', 'Vienna', 48.2100, 16.3634, 'VIE');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Azerbaijan', 'Baku', 40.4093, 49.8671, 'GYD');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Bahamas', 'Nassau', 25.0343, -77.3963, 'NAS');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Bahrain', 'Manama', 26.2285, 50.5860, 'BAH');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Bangladesh', 'Dhaka', 23.8103, 90.4125, 'DAC');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Barbados', 'Bridgetown', 13.0975, -59.6167, 'BGI');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Belarus', 'Minsk', 53.9045, 27.5615, 'MSQ');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Belgium', 'Brussels', 50.8503, 4.3517, 'BRU');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Belize', 'Belmopan', 17.2514, -88.7669, 'BZE');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Benin', 'Porto-Novo', 6.4969, 2.6289, 'COO');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Bhutan', 'Thimphu', 27.4712, 89.6419, 'PBH');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Bolivia', 'Sucre', -19.0333, -65.2627, 'VVI');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Bosnia and Herzegovina', 'Sarajevo', 43.8563, 18.4131, 'SJJ');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Botswana', 'Gaborone', -24.6282, 25.9231, 'GBE');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Brazil', 'Brasília', -15.7939, -47.8828, 'BSB');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Brunei', 'Bandar Seri Begawan', 4.9031, 114.9398, 'BWN');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Bulgaria', 'Sofia', 42.6977, 23.3219, 'SOF');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Burkina Faso', 'Ouagadougou', 12.3714, -1.5197, 'OUA');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Burundi', 'Gitega', -3.4264, 29.9306, 'BJM');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Cabo Verde', 'Praia', 14.9331, -23.5133, 'RAI');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Cambodia', 'Phnom Penh', 11.5564, 104.9282, 'PNH');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Cameroon', 'Yaoundé', 3.8480, 11.5021, 'NSI');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Canada', 'Ottawa', 45.4215, -75.6972, 'YOW');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Central African Republic', 'Bangui', 4.3947, 18.5582, 'BGF');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Chad', 'N Djamena', 12.1348, 15.0557, 'NDJ');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Chile', 'Santiago', -33.4489, -70.6693, 'SCL');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('China', 'Beijing', 39.9042, 116.4074, 'PEK');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Colombia', 'Bogotá', 4.7110, -74.0721, 'BOG');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Comoros', 'Moroni', -11.7172, 43.2473, 'HAH');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Congo, Democratic Republic of the', 'Kinshasa', -4.4419, 15.2663, 'FIH');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Congo, Republic of the', 'Brazzaville', -4.2634, 15.2429, 'BZV');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Costa Rica', 'San José', 9.9281, -84.0907, 'SJO');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Croatia', 'Zagreb', 45.8150, 15.9819, 'ZAG');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Cuba', 'Havana', 23.1136, -82.3666, 'HAV');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Cyprus', 'Nicosia', 35.1856, 33.3823, 'LCA');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Czech Republic', 'Prague', 50.0755, 14.4378, 'PRG');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Denmark', 'Copenhagen', 55.6761, 12.5683, 'CPH');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Djibouti', 'Djibouti', 11.8251, 42.5903, 'JIB');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Dominica', 'Roseau', 15.3092, -61.3794, 'DOM');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Dominican Republic', 'Santo Domingo', 18.4861, -69.9312, 'SDQ');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Ecuador', 'Quito', -0.1807, -78.4678, 'UIO');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Egypt', 'Cairo', 30.0444, 31.2357, 'CAI');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('El Salvador', 'San Salvador', 13.6929, -89.2182, 'SAL');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Equatorial Guinea', 'Malabo', 3.7500, 8.7833, 'SSG');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Eritrea', 'Asmara', 15.3229, 38.9251, 'ASM');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Estonia', 'Tallinn', 59.4370, 24.7535, 'TLL');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Eswatini', 'Mbabane', -26.3054, 31.1367, 'MTS');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Ethiopia', 'Addis Ababa', 9.0327, 38.7469, 'ADD');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Fiji', 'Suva', -18.1248, 178.4501, 'SUV');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Finland', 'Helsinki', 60.1695, 24.9355, 'HEL');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('France', 'Paris', 48.8566, 2.3522, 'CDG');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Gabon', 'Libreville', 0.4162, 9.4673, 'LBV');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Gambia', 'Banjul', 13.4549, -16.5790, 'BJL');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Georgia', 'Tbilisi', 41.7151, 44.8271, 'TBS');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Germany', 'Berlin', 52.5200, 13.4050, 'BER');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Ghana', 'Accra', 5.6037, -0.1870, 'ACC');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Greece', 'Athens', 37.9838, 23.7275, 'ATH');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Grenada', 'Saint Georges', 12.0561, -61.7486, 'GND');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Guatemala', 'Guatemala City', 14.6349, -90.5069, 'GUA');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Guinea', 'Conakry', 9.6412, -13.5784, 'CKY');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Guinea-Bissau', 'Bissau', 11.8590, -15.5950, 'OXB');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Guyana', 'Georgetown', 6.8013, -58.1551, 'GEO');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Haiti', 'Port-au-Prince', 18.5944, -72.3074, 'PAP');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Honduras', 'Tegucigalpa', 14.0723, -87.1921, 'TGU');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Hungary', 'Budapest', 47.4979, 19.0402, 'BUD');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Iceland', 'Reykjavik', 64.1355, -21.8954, 'KEF');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('India', 'New Delhi', 28.6139, 77.2090, 'DEL');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Indonesia', 'Jakarta', -6.2088, 106.8456, 'CGK');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Iran', 'Tehran', 35.6892, 51.3890, 'IKA');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Iraq', 'Baghdad', 33.3152, 44.3661, 'BGW');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Ireland', 'Dublin', 53.3498, -6.2603, 'DUB');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Israel', 'Jerusalem', 31.7683, 35.2137, 'TLV');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Italy', 'Rome', 41.9028, 12.4964, 'FCO');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Jamaica', 'Kingston', 17.9714, -76.7936, 'KIN');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Japan', 'Tokyo', 35.6762, 139.6503, 'HND');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Jordan', 'Amman', 31.9539, 35.9106, 'AMM');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Kazakhstan', 'Nur-Sultan', 51.1694, 71.4491, 'NQZ');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Kenya', 'Nairobi', -1.2864, 36.8172, 'NBO');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Kiribati', 'Tarawa', 1.3292, 172.9780, 'TRW');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Kuwait', 'Kuwait City', 29.3759, 47.9774, 'KWI');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Kyrgyzstan', 'Bishkek', 42.8746, 74.5698, 'FRU');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Laos', 'Vientiane', 17.9757, 102.6331, 'VTE');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Latvia', 'Riga', 56.9496, 24.1052, 'RIX');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Lebanon', 'Beirut', 33.8938, 35.5018, 'BEY');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Lesotho', 'Maseru', -29.3150, 27.4869, 'MSU');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Liberia', 'Monrovia', 6.3000, -10.7970, 'ROB');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Libya', 'Tripoli', 32.8872, 13.1913, 'TIP');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Liechtenstein', 'Vaduz', 47.1410, 9.5209, 'ACH');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Lithuania', 'Vilnius', 54.6872, 25.2797, 'VNO');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Luxembourg', 'Luxembourg City', 49.6117, 6.1319, 'LUX');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Madagascar', 'Antananarivo', -18.8792, 47.5079, 'TNR');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Malawi', 'Lilongwe', -13.9626, 33.7741, 'LLW');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Malaysia', 'Kuala Lumpur', 3.1390, 101.6869, 'KUL');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Maldives', 'Malé', 4.1755, 73.5093, 'MLE');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Mali', 'Bamako', 12.6392, -8.0029, 'BKO');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Malta', 'Valletta', 35.8997, 14.5147, 'MLA');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Marshall Islands', 'Majuro', 7.0648, 171.2695, 'MAJ');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Mauritania', 'Nouakchott', 18.0735, -15.9582, 'NKC');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Mauritius', 'Port Louis', -20.1609, 57.5012, 'MRU');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Mexico', 'Mexico City', 19.4326, -99.1332, 'MEX');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Micronesia', 'Palikir', 6.9248, 158.1610, 'PNI');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Moldova', 'Chișinău', 47.0105, 28.8638, 'KIV');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Monaco', 'Monaco', 43.7384, 7.4246, 'MCM');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Mongolia', 'Ulaanbaatar', 47.8864, 106.9057, 'ULN');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Montenegro', 'Podgorica', 42.4416, 19.2662, 'TGD');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Morocco', 'Rabat', 34.0209, -6.8416, 'RBA');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Mozambique', 'Maputo', -25.9692, 32.5732, 'MPM');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Myanmar', 'Naypyidaw', 19.7633, 96.0785, 'NYT');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Namibia', 'Windhoek', -22.5609, 17.0658, 'WDH');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Nauru', 'Yaren', -0.5477, 166.9209, 'INU');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Nepal', 'Kathmandu', 27.7172, 85.3240, 'KTM');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Netherlands', 'Amsterdam', 52.3676, 4.9041, 'AMS');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('New Zealand', 'Wellington', -41.2865, 174.7762, 'WLG');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Nicaragua', 'Managua', 12.1140, -86.2362, 'MGA');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Niger', 'Niamey', 13.5116, 2.1254, 'NIM');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Nigeria', 'Abuja', 9.0765, 7.3986, 'ABV');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('North Korea', 'Pyongyang', 39.0392, 125.7625, 'FNJ');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('North Macedonia', 'Skopje', 41.9973, 21.4280, 'SKP');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Norway', 'Oslo', 59.9139, 10.7522, 'OSL');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Oman', 'Muscat', 23.5880, 58.3829, 'MCT');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Pakistan', 'Islamabad', 33.6844, 73.0479, 'ISB');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Palau', 'Ngerulmud', 7.5004, 134.6233, 'ROR');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Panama', 'Panama City', 8.9824, -79.5199, 'PTY');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Papua New Guinea', 'Port Moresby', -9.4438, 147.1803, 'POM');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Paraguay', 'Asunción', -25.2637, -57.5759, 'ASU');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Peru', 'Lima', -12.0464, -77.0428, 'LIM');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Philippines', 'Manila', 14.5995, 120.9842, 'MNL');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Poland', 'Warsaw', 52.2297, 21.0122, 'WAW');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Portugal', 'Lisbon', 38.7223, -9.1393, 'LIS');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Qatar', 'Doha', 25.2760, 51.2272, 'DOH');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Romania', 'Bucharest', 44.4268, 26.1025, 'OTP');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Russia', 'Moscow', 55.7558, 37.6176, 'SVO');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Rwanda', 'Kigali', -1.9579, 30.1127, 'KGL');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Saint Kitts and Nevis', 'Basseterre', 17.3026, -62.7177, 'SKB');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Saint Lucia', 'Castries', 14.0101, -60.9875, 'SLU');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Saint Vincent and the Grenadines', 'Kingstown', 13.1600, -61.2248, 'SVD');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Samoa', 'Apia', -13.8333, -171.7500, 'APW');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('San Marino', 'San Marino', 43.9333, 12.4500, 'RMI');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Sao Tome and Principe', 'São Tomé', 0.3365, 6.7273, 'TMS');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Saudi Arabia', 'Riyadh', 24.7136, 46.6753, 'RUH');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Senegal', 'Dakar', 14.7167, -17.4677, 'DKR');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Serbia', 'Belgrade', 44.7866, 20.4489, 'BEG');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Seychelles', 'Victoria', -4.6191, 55.4513, 'SEZ');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Sierra Leone', 'Freetown', 8.4657, -13.2317, 'FNA');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Singapore', 'Singapore', 1.3521, 103.8198, 'SIN');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Slovakia', 'Bratislava', 48.1486, 17.1077, 'BTS');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Slovenia', 'Ljubljana', 46.0569, 14.5058, 'LJU');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Solomon Islands', 'Honiara', -9.4456, 159.9729, 'HIR');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Somalia', 'Mogadishu', 2.0469, 45.3182, 'MGQ');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('South Africa', 'Pretoria', -25.7479, 28.2293, 'PRY');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('South Korea', 'Seoul', 37.5665, 126.9780, 'ICN');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('South Sudan', 'Juba', 4.8594, 31.5713, 'JUB');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Spain', 'Madrid', 40.4168, -3.7038, 'MAD');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Sri Lanka', 'Sri Jayawardenepura Kotte', 6.9271, 79.8612, 'CMB');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Sudan', 'Khartoum', 15.5007, 32.5599, 'KRT');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Suriname', 'Paramaribo', 5.8520, -55.2038, 'PBM');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Sweden', 'Stockholm', 59.3293, 18.0686, 'ARN');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Switzerland', 'Bern', 46.9481, 7.4474, 'BRN');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Syria', 'Damascus', 33.5138, 36.2765, 'DAM');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Taiwan', 'Taipei', 25.0330, 121.5654, 'TPE');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Tajikistan', 'Dushanbe', 38.5598, 68.7870, 'DYU');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Tanzania', 'Dodoma', -6.1620, 35.7516, 'DAR');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Thailand', 'Bangkok', 13.7563, 100.5018, 'BKK');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Togo', 'Lomé', 6.1725, 1.2314, 'LFW');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Tonga', 'Nukualofa', -21.1393, -175.2048, 'TBU');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Trinidad and Tobago', 'Port of Spain', 10.6549, -61.5019, 'POS');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Tunisia', 'Tunis', 36.8065, 10.1815, 'TUN');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Turkey', 'Ankara', 39.9334, 32.8597, 'ESB');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Turkmenistan', 'Ashgabat', 37.9601, 58.3261, 'ASB');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Tuvalu', 'Funafuti', -8.5243, 179.1942, 'FUN');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Uganda', 'Kampala', 0.3476, 32.5825, 'EBB');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Ukraine', 'Kyiv', 50.4501, 30.5234, 'KBP');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('United Arab Emirates', 'Abu Dhabi', 24.4539, 54.3773, 'AUH');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('United Kingdom', 'London', 51.5074, -0.1278, 'LHR');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('United States', 'Washington, D.C.', 38.9072, -77.0369, 'DCA');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Uruguay', 'Montevideo', -34.9011, -56.1645, 'MVD');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Uzbekistan', 'Tashkent', 41.2995, 69.2401, 'TAS');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Vanuatu', 'Port Vila', -17.7333, 168.3273, 'VLI');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Vatican City', 'Vatican City', 41.9029, 12.4534, 'FCO');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Venezuela', 'Caracas', 10.4806, -66.9036, 'CCS');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Vietnam', 'Hanoi', 21.0285, 105.8542, 'HAN');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Yemen', 'Sana', 15.3694, 44.1910, 'SAH');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Zambia', 'Lusaka', -15.3875, 28.3228, 'LUN');
INSERT INTO capital_cities (country, city, latitude, longitude, airport_code) VALUES ('Zimbabwe', 'Harare', -17.8252, 31.0335, 'HRE');
